[phases.setup]
nixpkgsArchive = "23.05"

[phases.install]
cmds = [
  "apt-get update",
  "apt-get install -y supervisor",
  "curl -fsSL https://get.caddyserver.com | bash",
  "composer install --no-dev --optimize-autoloader",
  "npm ci",
  "npm run build",
  "php artisan storage:link",
  "chmod -R 775 storage",
  "chmod -R 775 bootstrap/cache",
  "php artisan key:generate --force",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[phases.build]
cmds = [
  "echo 'Build phase complete'"
]

[start]
cmd = "supervisord -c supervisord.conf"