[phases.setup]
nixPkgs = ['openssl', 'nodejs', 'php81', 'php81Packages.composer']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']

[phases.build]
cmds = [
  'php artisan config:cache',
  'php artisan route:cache',
  'php artisan view:cache',
  'npm ci && npm run build'  # If using frontend assets
]

[start]
cmd = 'php artisan websockets:serve --host=0.0.0.0 --port=${PORT:-6001}'