[phases.setup]
nixpkgsArchive = "23.05"

[phases.install]
cmds = [
  "apt-get update",
  "apt-get install -y supervisor",
  "composer install --no-dev --optimize-autoloader",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  "mkdir -p /etc/supervisor/conf.d"
]

[phases.build]
cmds = [
  "npm ci",
  "npm run build"
]

[start]
cmd = "supervisord -c supervisord.conf"
